language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    # perform a linux build
    - name: Linux Build
      services: docker

    # and a mac build
    - name: MacOS Build
      os: osx
      language: shell

    # and a windows build
    - name: Windows Build
      os: windows
      language: shell

      before_install:
        # install python
        - choco install python --version 3.8.0
        # add python to path
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # python -> python3
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

install:
  # install gd.py with required plugins
  - python3 -m pip install --upgrade .[image,lint,speedups,test]
  # install coveralls
  - python3 -m pip install --upgrade coveralls
  # install cibuildwheel
  - python3 -m pip install --upgrade cibuildwheel
  # install setuptools_rust
  - python3 -m pip install --upgrade setuptools_rust

script:
  # run lint
  - python3 -m flake8
  # run tests and check coverage
  - python3 -m coverage run -m pytest ./tests/ --disable-warnings
  # configure wheel builder
  - export CIBW_BEFORE_BUILD="source ./ci/install_rust.sh"
  - export CIBW_ENVIRONMENT="PATH='$HOME/rust/bin:$PATH'"
  # build wheels
  - python3 -m cibuildwheel --output-dir built_wheels

after_success:
  # report to coveralls
  - python3 -m coveralls
  # if the release was tagged, upload wheels
  - if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install --upgrade twine
      python3 -m twine upload built_wheels/*.whl
    fi
